import './globals.css';
import type { Metadata } from 'next'
import { FC, ReactNode } from "react";

import Navigation from "@common/Navigation";
import Footer from "@common/Footer";
import { montserrat, quicksand } from "@utils/font";



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IRootLayout {
  children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${quicksand.variable} font-sans`}>
        <Navigation />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html >
  )
}

export default RootLayout;