import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { FC, ReactNode } from "react";

import Navigation from "@common/Navigation";
import Footer from "@common/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface IRootLayout {
  children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="en" >
      <body>
        <Navigation />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}

export default RootLayout;